[package]
name = "prjcombine-versal"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true

[lints]
workspace = true
