[package]
name = "prjcombine_xc5200_rdverify"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_rawdump.workspace = true
prjcombine_rdverify.workspace = true
prjcombine-xc2000.workspace = true
prjcombine_xc2000_naming.workspace = true

[lints]
workspace = true
