[package]
name = "prjcombine-re-xilinx-rd2db-virtex2"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-virtex2.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true
prjcombine-re-xilinx-naming.workspace = true
prjcombine-re-xilinx-naming-virtex2.workspace = true
prjcombine-re-xilinx-rd2db-interconnect.workspace = true
prjcombine-re-xilinx-rd2db-grid.workspace = true

[lints]
workspace = true
