[package]
name = "prjcombine-ecp"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
jzon.workspace = true
zstd.workspace = true
bincode.workspace = true
itertools.workspace = true
unnamed_entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true

[lints]
workspace = true
