[package]
name = "prjcombine-ultrascale"
version.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace = true
jzon.workspace = true
zstd.workspace = true
bincode.workspace = true
unnamed_entity.workspace = true
bimap.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true

[lints]
workspace = true
