[package]
name = "prjcombine-re-xilinx-rdverify-ultrascale"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-ultrascale.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true
prjcombine-re-xilinx-naming.workspace = true
prjcombine-re-xilinx-naming-ultrascale.workspace = true
prjcombine-re-xilinx-rdverify.workspace = true

[lints]
workspace = true
