[package]
name = "prjcombine-re-xilinx-ise-dump"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
simple-error.workspace = true
tempfile.workspace = true
regex.workspace = true
rayon.workspace = true
clap.workspace = true
prjcombine-re-toolchain.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true
prjcombine-re-xilinx-rdbuild.workspace = true

[lints]
workspace = true
