[package]
name = "prjcombine_ultrascale_rd2db"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-ultrascale.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine_rdintb.workspace = true
prjcombine_rdgrid.workspace = true
prjcombine_rawdump.workspace = true
prjcombine_ultrascale_naming.workspace = true
enum-map.workspace = true

[lints]
workspace = true
