[package]
name = "prjcombine-re-harvester"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-types.workspace = true

[lints]
workspace = true
