[package]
name = "prjcombine_xilinx_finish"
edition.workspace = true
version.workspace = true

[[bin]]
name = "xilinx_finish"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true
itertools.workspace = true
regex.workspace = true
clap.workspace = true
unnamed_entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-xc2000.workspace = true
prjcombine-virtex.workspace = true
prjcombine-virtex2.workspace = true
prjcombine-spartan6.workspace = true
prjcombine-virtex4.workspace = true
prjcombine-ultrascale.workspace = true
prjcombine_xact_geom.workspace = true
prjcombine_xilinx_geom.workspace = true

[lints]
workspace = true
