[package]
name = "prjcombine-jed"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bitvec.workspace = true

[lints]
workspace = true
