[package]
name = "prjcombine-xpla3"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
serde.workspace = true
zstd.workspace = true
bincode.workspace = true
clap.workspace = true
jzon.workspace = true
prjcombine-types.workspace = true
prjcombine-jed.workspace = true

[lints]
workspace = true
