[workspace]
resolver = "3"
members = [
    "types",
    "interconnect",
    "jed",
    "siliconblue",
    "xilinx-bitstream",
    "xc2000",
    "virtex",
    "virtex2",
    "spartan6",
    "virtex4",
    "ultrascale",
    "versal",
    "ecp",
    "xc9500",
    "xpla3",
    "coolrunner2",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "0BSD OR Apache-2.0"
repository = "https://github.com/prjunnamed/prjcombine"
authors = []

[workspace.dependencies]
prjcombine-types = { path = "types" }
prjcombine-interconnect = { path = "interconnect" }
prjcombine-jed = { path = "jed" }
prjcombine-xilinx-bitstream = { path = "xilinx-bitstream" }
jzon = "0.12"
bincode = "2.0"
unnamed_entity = { version = "0.1.7", features = ["bitvec", "map", "bincode"] }
bitvec = "1.0"
itertools = "0.14"
arrayvec = "0.7.6"
ndarray = "0.16"
bimap = "0.6"
arrayref = "0.3.6"
des = "0.8.1"
cbc = "0.1.2"
aes = "0.8.4"
sha2 = "0.10.8"
assert_matches = "1.5"
clap = "4.1"
zstd = "0.13"

[profile.dev]
opt-level = 2
overflow-checks = false
debug-assertions = false
debug = 2

[workspace.lints.clippy]
collapsible_else_if = "allow"
bool_to_int_with_if = "allow"
needless_range_loop = "allow"
assigning_clones = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"
precedence = "allow"
