[package]
name = "prjcombine-re-lattice-rd2geom"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "lrd2geom"
path = "src/main.rs"

[dependencies]
arrayref.workspace = true
flate2.workspace = true
clap.workspace = true
rayon.workspace = true
unnamed_entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-ecp.workspace = true
prjcombine-re-lattice-rawdump.workspace = true
prjcombine-re-lattice-naming.workspace = true

[lints]
workspace = true
