[package]
name = "prjcombine_harvester"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine_types.workspace = true
bitvec.workspace = true

[lints]
workspace = true
