[package]
name = "prjcombine-re-xilinx-cpld"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-types.workspace = true
prjcombine-xc9500.workspace = true
prjcombine-xpla3.workspace = true
prjcombine-coolrunner2.workspace = true
prjcombine-re-toolchain.workspace = true
prjcombine-re-hammer.workspace = true
prjcombine-re-sdf.workspace = true
prjcombine-re-xilinx-ise-dump.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true
clap.workspace = true
tempfile.workspace = true
simple-error.workspace = true
itertools.workspace = true
bitvec.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
enum-map.workspace = true


[lints]
workspace = true
