[package]
name = "prjcombine-re-xilinx-xdl"
version.workspace = true
edition.workspace = true

[dependencies]
tempfile.workspace = true
arrayref.workspace = true
prjcombine-re-toolchain.workspace = true

[dev-dependencies]
clap.workspace = true

[lints]
workspace = true
