[package]
name = "prjcombine_virtex2_naming"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine-virtex2.workspace = true

[lints]
workspace = true
