[package]
name = "prjcombine-re-xilinx-naming-versal"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
enum-map.workspace = true
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-versal.workspace = true
prjcombine-re-xilinx-naming.workspace = true

[lints]
workspace = true
