[package]
name = "prjcombine_virtex_bitstream"
version.workspace = true
edition.workspace = true

[dependencies]
arrayvec.workspace = true
bitvec.workspace = true
enum-map.workspace = true
arrayref.workspace = true
unnamed_entity.workspace = true
prjcombine_int.workspace = true
des.workspace = true
cbc.workspace = true
aes.workspace = true
sha2.workspace = true

[lints]
workspace = true
