[package]
name = "prjcombine_spartan6_rd2db"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine_rdintb.workspace = true
prjcombine_rdgrid.workspace = true
prjcombine_rawdump.workspace = true
prjcombine-spartan6.workspace = true
prjcombine_spartan6_naming.workspace = true

[lints]
workspace = true
