[package]
name = "prjcombine_xc2000_naming"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine-xc2000.workspace = true

[lints]
workspace = true
