[package]
name = "prjcombine-re-xilinx-naming-spartan6"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-spartan6.workspace = true
prjcombine-re-xilinx-naming.workspace = true

[lints]
workspace = true
