[package]
name = "prjcombine-re-xilinx-rdverify-spartan6"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-spartan6.workspace = true
prjcombine-re-xilinx-rawdump.workspace = true
prjcombine-re-xilinx-naming.workspace = true
prjcombine-re-xilinx-naming-spartan6.workspace = true
prjcombine-re-xilinx-rdverify.workspace = true

[lints]
workspace = true
