[package]
name = "prjcombine-siliconblue"
edition.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
enum-map.workspace = true
bitvec.workspace = true
itertools.workspace = true
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
serde_json.workspace = true
unnamed_entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true

[lints]
workspace = true
