[package]
name = "prjcombine_virtex_rdverify"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_rawdump.workspace = true
prjcombine_rdverify.workspace = true
prjcombine-virtex.workspace = true
prjcombine_virtex_naming.workspace = true

[lints]
workspace = true
