[package]
name = "prjcombine_rdgrid"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_rawdump.workspace = true

[lints]
workspace = true
