[package]
name = "prjcombine_xilinx_rdis"
edition.workspace = true
version.workspace = true

[[bin]]
name = "xrdis"
path = "src/main.rs"

[dependencies]
clap.workspace = true
arrayref.workspace = true
prjcombine-xilinx-bitstream.workspace = true
prjcombine_xilinx_geom.workspace = true

[lints]
workspace = true
