[package]
name = "prjcombine_xilinx_geom"
version.workspace = true
edition.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-types.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-xilinx-bitstream.workspace = true
prjcombine-xc2000.workspace = true
prjcombine-virtex.workspace = true
prjcombine-virtex2.workspace = true
prjcombine-spartan6.workspace = true
prjcombine-virtex4.workspace = true
prjcombine-ultrascale.workspace = true
prjcombine-versal.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine_xc2000_naming.workspace = true
prjcombine_virtex_naming.workspace = true
prjcombine_virtex2_naming.workspace = true
prjcombine_spartan6_naming.workspace = true
prjcombine_virtex4_naming.workspace = true
prjcombine_ultrascale_naming.workspace = true
prjcombine_versal_naming.workspace = true
serde.workspace = true
bincode.workspace = true
zstd.workspace = true
clap.workspace = true
rayon.workspace = true
itertools.workspace = true

[lints]
workspace = true
