[package]
name = "prjcombine_spartan6_naming"
edition.workspace = true
version.workspace = true

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine-spartan6.workspace = true

[lints]
workspace = true
