[package]
name = "prjcombine_xilinx_rd2geom"
version.workspace = true
edition.workspace = true

[[bin]]
name = "xrd2geom"
path = "src/main.rs"

[dependencies]
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine_xilinx_naming.workspace = true
prjcombine_rdintb.workspace = true
prjcombine_rdgrid.workspace = true
prjcombine_rdverify.workspace = true
prjcombine_xilinx_geom.workspace = true
prjcombine_rawdump.workspace = true
prjcombine_xc2000_naming.workspace = true
prjcombine_xc4000_rdverify.workspace = true
prjcombine_xc4000_rd2db.workspace = true
prjcombine_xc5200_rdverify.workspace = true
prjcombine_xc5200_rd2db.workspace = true
prjcombine_virtex_naming.workspace = true
prjcombine_virtex_rdverify.workspace = true
prjcombine_virtex_rd2db.workspace = true
prjcombine-virtex2.workspace = true
prjcombine_virtex2_naming.workspace = true
prjcombine_virtex2_rdverify.workspace = true
prjcombine_virtex2_rd2db.workspace = true
prjcombine_spartan6_naming.workspace = true
prjcombine_spartan6_rd2db.workspace = true
prjcombine_spartan6_rdverify.workspace = true
prjcombine-virtex4.workspace = true
prjcombine_virtex4_naming.workspace = true
prjcombine_virtex4_rdverify.workspace = true
prjcombine_virtex4_rd2db.workspace = true
prjcombine_virtex5_rdverify.workspace = true
prjcombine_virtex5_rd2db.workspace = true
prjcombine_virtex6_rdverify.workspace = true
prjcombine_virtex6_rd2db.workspace = true
prjcombine_virtex7_rdverify.workspace = true
prjcombine_virtex7_rd2db.workspace = true
prjcombine-ultrascale.workspace = true
prjcombine_ultrascale_naming.workspace = true
prjcombine_ultrascale_rdverify.workspace = true
prjcombine_ultrascale_rd2db.workspace = true
prjcombine-versal.workspace = true
prjcombine_versal_naming.workspace = true
prjcombine_versal_rdverify.workspace = true
prjcombine_versal_rd2db.workspace = true
clap.workspace = true
simple-error.workspace = true
serde.workspace = true
enum-map.workspace = true
std-semaphore.workspace = true

[lints]
workspace = true
