[package]
name = "prjcombine_xact_geom"
edition.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
zstd.workspace = true
bincode.workspace = true
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true
prjcombine-xilinx-bitstream.workspace = true
prjcombine-xc2000.workspace = true
prjcombine_xc2000_xact.workspace = true
prjcombine_xact_naming.workspace = true

[lints]
workspace = true
