[package]
name = "prjcombine-re-xilinx-xact-naming"
edition.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
unnamed_entity.workspace = true
prjcombine-interconnect.workspace = true

[lints]
workspace = true
